services:
  nginx:
    image: nginx:latest
    container_name: deliverycenter-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf #app,web and admin panel
      - ./docker/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf #app
      - ./.data/nginx/logs:/var/log/nginx
      - ./src:/var/www/app
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - deliverycenter_network
    environment:
      - X_SERVER_TYPE=nginx

  api:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: deliverycenter-app
    volumes:
      - ./src:/var/www/app
    restart: always
    networks:
      - deliverycenter_network
    environment:
      - X_SERVER_TYPE=api

  redis:
    image: redis:latest
    container_name: deliverycenter-redis
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      - deliverycenter_network

  database:
    image: mysql:8.0
    container_name: deliverycenter_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.data/mysql_data:/var/lib/mysql
      # - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - deliverycenter_network
    command: --default-authentication-plugin=mysql_native_password

  mailpit:
    image: axllent/mailpit
    container_name: deliverycenter-mailpit
    ports:
      - 1025:1025 # SMTP server
      - 8026:8025 # Web UI
    networks:
      - deliverycenter_network

volumes:
  redis:
    driver: local

networks:
  deliverycenter_network:
    driver: bridge
